name: Send-Random-Image

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x send_image.sh

      - name: Run Bash script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./send_image.sh