name: Send-Random-Image

on:
  workflow_dispatch:
  
jobs:
  send:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x send_image.sh

      - name: Download previous sent log
        uses: actions/download-artifact@v4
        with:
          name: sent-log
          path: .
        continue-on-error: true

      - name: Run Bash script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./send_image.sh


      - name: Verify sent.log
        run: |
          echo "Checking sent.log"
          test -f sent.log && cat sent.log || (echo "sent.log NOT found!" && exit 1)


      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: sent-log
          path: sent.log
